## 파일 입출력

In [69]:
import os 
os.getcwd()

'C:\\Users\\j2hoo\\OneDrive\\Desktop\\multicampus28\\python\\ml'

In [70]:
import pandas as pd 

sample_df = pd.DataFrame({"col1" : [1, 2], "col2" : [3, 4]})
sample_df # 파일명 test.csv index=False

sample_df.to_csv("output/sample/test.csv", index=False)

## 파일 불러오기
- sample 폴더 안에 test.csv


In [71]:
df = pd.read_csv(filepath_or_buffer="./output/sample/test.csv")
df

col1  col2
0     1     3
1     2     4

In [72]:
df_boston = pd.read_csv("./data/boston.csv")
df_boston.head(1)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

## 열 및 행선택
- CRIM, ZN, INDUS 열을 선택함

In [73]:
cols = ['CRIM', 'ZN', 'INDUS']
result = df_boston[cols]
result.head(1)

CRIM    ZN  INDUS
0  0.00632  18.0   2.31

- ZN이 18.0에 해당하는 행만 추출

In [74]:
# 행 추출의 기본원리는 조건문
result = df_boston[df_boston['ZN'] == 18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

- AGE가 50이상인 데이터만 추출

In [75]:
result = df_boston[df_boston['AGE'] >= 50].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
4    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
354  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
355  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
356  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
357  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
358  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  396.90   5.33    36.2  
4       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
354     21.0  391.99   9.67    22.4  
355     21.0  396.90   9.08    20.6  
356     21.0  396.90   5.64    23.9  
357     21.0  393.45   6.48    22.0  
358     21.0  396.90   7.88    11.9  

[359 rows x 14 columns]

- INDUS가 5.0 이상이면서 B가 394이상인 데이터 추출

In [76]:
df_boston[df_boston['target']>=22]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
5    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
494  0.27957   0.0   9.69   0.0  0.585  5.926  42.6  2.3817  6.0  391.0   
495  0.17899   0.0   9.69   0.0  0.585  5.670  28.8  2.7986  6.0  391.0   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
5       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
494     19.2  396.90  13.59    24.5  
495     19.2  393.29  17.60    23.1  
501     21.0  391.99   9.67    22.4  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  

[229 rows x 14 columns]

In [77]:
result = df_boston[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394) & (df_boston['target']>=22)]
# result = df_boston[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394)]
result.head(1)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
6  0.08829  12.5   7.87   0.0  0.524  6.012  66.6  5.5605  5.0  311.0   

   PTRATIO      B  LSTAT  target  
6     15.2  395.6  12.43    22.9

## iloc와 loc 문법
- iloc ~~~
- loc ~~~ 

In [78]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [79]:
%%timeit

# iloc 활용해서 추출
result = df_boston.iloc[0:3, 0:3]
result

180 µs ± 37.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [80]:
%%timeit 

# loc 활용해서 추출
result = df_boston.loc[0:2, ["CRIM", "ZN", "INDUS"]]
result

# 슬랙 저에게 DM으로 코드 전송 후, 쉬세요. 못하신 분은 50분까지 실습하시고 10분 쉬세요. 

1.32 ms ± 274 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [81]:
result = df_boston.loc[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394) # 행 
                       , ["CRIM", "ZN", "INDUS"]].reset_index(drop=True) # 열
result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.08829  12.5   7.87
2    0.14455  12.5   7.87
3    0.11747  12.5   7.87
4    0.62976   0.0   8.14
..       ...   ...    ...
138  0.17783   0.0   9.69
139  0.22438   0.0   9.69
140  0.04527   0.0  11.93
141  0.06076   0.0  11.93
142  0.04741   0.0  11.93

[143 rows x 3 columns]

## 결측치 다루기

In [93]:
import pandas as pd 
import numpy as np

np.random.seed(0) # 실험조건 동일하게 맞추기 위해 
data = np.random.randint(0, 10, size=(10, 3)).astype(float)
print(data)

[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 7. 6.]
 [8. 8. 1.]
 [6. 7. 7.]
 [8. 1. 5.]
 [9. 8. 9.]
 [4. 3. 0.]
 [3. 5. 0.]]


In [94]:
data[data < 3] = np.nan
print(data)

[[ 5. nan  3.]
 [ 3.  7.  9.]
 [ 3.  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4.  3. nan]
 [ 3.  5. nan]]


In [95]:
df = pd.DataFrame(data,columns=["col1", "col2", "col3"]) # 외부에서 새로운 데이터 가져옴

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     float64
 1   col2    8 non-null      float64
 2   col3    6 non-null      float64
dtypes: float64(3)
memory usage: 368.0 bytes


In [96]:
df.isna().sum()

col1    0
col2    2
col3    4
dtype: int64

In [100]:
# 평균으로 대치 해보기
col3_mean = df['col3'].mean()

df['col3'] = df['col3'].fillna(col3_mean)
df['col2'] = df['col2'].fillna(df['col2'].mean())
df

col1  col2  col3
0   5.0  6.25   3.0
1   3.0  7.00   9.0
2   3.0  5.00   6.5
3   4.0  7.00   6.0
4   8.0  8.00   6.5
5   6.0  7.00   7.0
6   8.0  6.25   5.0
7   9.0  8.00   9.0
8   4.0  3.00   6.5
9   3.0  5.00   6.5

In [102]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})
df 

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

## 행추가 

In [103]:
df.loc[6, "이름":"영어"] = ["Kim", 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     Kim   50.0   60.0

In [110]:
%%timeit

def calculate_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    else:
        return 'F'
df['등급'] = df['국어'].apply(lambda x: calculate_grade(x))

541 µs ± 40.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [107]:
%%timeit 

df['등급'] = df['국어'].apply(lambda score: 'A' if score >= 90 else ('B' if score >= 80 else ('C' if score >= 70 else 'F')))
df

519 µs ± 39.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [108]:
%%timeit 

df['등급'] = ''

for i in range(0, df.shape[0]):
    if df.loc[i, '국어'] >= 90:
        df.loc[i, '등급'] = "A"
    elif df.loc[i, '국어'] >= 80:
        df.loc[i, '등급'] = "B"
    elif df.loc[i, '국어'] >= 70:
        df.loc[i, '등급'] = "C"
    else:
        df.loc[i, '등급'] = "F"
df

1.57 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# 국어점수가 90점 이상이면 "A"
# 국어점수가 80점~89점 "B"
# 국어점수가 70점~79점 "C"
# 나머지는 F

- numpy.where, 조건식 한번만 적용
if 조건식, 참일 때, 거짓일 때

In [ ]:
# np.where(조건식, 참, np.where(조건식, 참, (np.where(조건식, 참))))
# np.select(다중조건식, 다중결괏값, default==> else 조건)

In [114]:
%%timeit

condition_list = [(df["국어"] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list    = ["A",                 "B",                                    "C"]
df['점수'] = np.select(condition_list, choice_list, default = "F")
df

2.88 ms ± 695 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 날짜 데이터 핸들링

In [120]:
date_string = "2023-03-02"
print(type(date_string))

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

<class 'str'>
2023-03-02 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [121]:
date_list = ["2023-03-02"]
print(type(date_list))

datetime_obj = pd.to_datetime(date_list)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>
DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기 
- raw_sales.csv 파일 가져오기

In [127]:
sales = pd.read_csv("data/raw_sales.csv")
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [123]:
# 날짜 데이터 변환
sales.head(1)

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4

In [134]:
sales['datesold'] = pd.to_datetime(sales['datesold'])
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB


In [141]:
# 연도, 월, 일 ===> 2시 5분까지 실습, 2시 5분에 출첵 할게요! 각자 알아서 10분 쉬세요!!
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


## shift 기능

In [144]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head(3)

datesold   price
0 2007-02-07  525000
1 2007-02-27  290000
2 2007-03-07  328000

In [149]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df.head(1)

datesold   price  shifted_v1    diff  shifted_v2
0 2007-02-07  525000           0  525000           0

In [151]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head(1)

datesold   price  shifted_v1    diff  shifted_v2   diff2
0 2007-02-07  525000           0  525000           0  525000

In [153]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()

temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)
temp_df.tail()

datesold   price  shifted_v3  shifted_v4
29575 2019-07-25  500000      560000      464950
29576 2019-07-25  560000      464950      589000
29577 2019-07-26  464950      589000      775000
29578 2019-07-26  589000      775000           0
29579 2019-07-26  775000           0           0

In [154]:
temp_df.head()

datesold   price  shifted_v3  shifted_v4
0 2007-02-07  525000      290000      328000
1 2007-02-27  290000      328000      380000
2 2007-03-07  328000      380000      310000
3 2007-03-09  380000      310000      465000
4 2007-03-21  310000      465000      399000

In [156]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


In [159]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head(3)

datesold  postcode   price propertyType  bedrooms  year  month  day  \
0 2007-02-07      2607  525000        house         4  2007      2    7   
1 2007-02-27      2906  290000        house         3  2007      2   27   
2 2007-03-07      2905  328000        house         3  2007      3    7   

            한글날짜  
0  2007년 02월 07일  
1  2007년 02월 27일  
2  2007년 03월 07일

## 결측치 이상치 데이터 핸들링

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [2]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals.head(1)

iso_code    lastdate     location  total_cases  total_deaths  \
0      AFG  2020-06-01  Afghanistan        15205           257   

   total_cases_pm  total_deaths_pm  population  pop_density  median_age  \
0         390.589            6.602  38928341.0       54.422        18.6   

   gdp_per_capita  hosp_beds  
0        1803.987        0.5

In [4]:
covidtotals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   iso_code         210 non-null    object 
 1   lastdate         210 non-null    object 
 2   location         210 non-null    object 
 3   total_cases      210 non-null    int64  
 4   total_deaths     210 non-null    int64  
 5   total_cases_pm   209 non-null    float64
 6   total_deaths_pm  209 non-null    float64
 7   population       210 non-null    float64
 8   pop_density      198 non-null    float64
 9   median_age       186 non-null    float64
 10  gdp_per_capita   182 non-null    float64
 11  hosp_beds        164 non-null    float64
dtypes: float64(7), int64(2), object(3)
memory usage: 19.8+ KB


In [3]:
pd.set_option('display.width', 40)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
covidtotals = covidtotals.set_index('iso_code')
covidtotals.head()

lastdate     location  \
iso_code                            
AFG       2020-06-01  Afghanistan   
ALB       2020-06-01      Albania   
DZA       2020-06-01      Algeria   
AND       2020-06-01      Andorra   
AGO       2020-06-01       Angola   

          total_cases  total_deaths  \
iso_code                              
AFG             15205           257   
ALB              1137            33   
DZA              9394           653   
AND               764            51   
AGO                86             4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   

            population  pop_density  \
iso_code                              
AFG      38,928,341.00        54.42   
ALB       2,877,800.00       104.87   
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   
AGO      32,866,268.00        23.89   

          median_age  gdp_per_capita  \
iso_code                               
AFG            18.60        1,803.99   
ALB            38.00       11,803.43   
DZA            29.10       13,913.84   
AND              NaN             NaN   
AGO            16.80        5,819.49   

          hosp_beds  
iso_code             
AFG            0.50  
ALB            2.89  
DZA            1.90  
AND             NaN  
AGO             NaN

In [15]:
covidtotals.head()

lastdate     location  \
iso_code                            
AFG       2020-06-01  Afghanistan   
ALB       2020-06-01      Albania   
DZA       2020-06-01      Algeria   
AND       2020-06-01      Andorra   
AGO       2020-06-01       Angola   

          total_cases  total_deaths  \
iso_code                              
AFG             15205           257   
ALB              1137            33   
DZA              9394           653   
AND               764            51   
AGO                86             4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   

            population  pop_density  \
iso_code                              
AFG      38,928,341.00        54.42   
ALB       2,877,800.00       104.87   
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   
AGO      32,866,268.00        23.89   

          median_age  gdp_per_capita  \
iso_code                               
AFG            18.60        1,803.99   
ALB            38.00       11,803.43   
DZA            29.10       13,913.84   
AND              NaN             NaN   
AGO            16.80        5,819.49   

          hosp_beds  
iso_code             
AFG            0.50  
ALB            2.89  
DZA            1.90  
AND             NaN  
AGO             NaN

### 결측치 처리
- 인구통계 컬럼에서 결측치 데이터를 확인
- 컬럼방향으로 결측치의 갯수를 파악함
- 5가지 인구 통계 변수 중에서 3개가 누락된 곳, 4개가 누락된 곳 확인

In [5]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']

In [6]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [7]:
covidtotals.iloc[2:4, :]

lastdate location  \
iso_code                        
DZA       2020-06-01  Algeria   
AND       2020-06-01  Andorra   

          total_cases  total_deaths  \
iso_code                              
DZA              9394           653   
AND               764            51   

          total_cases_pm  \
iso_code                   
DZA               214.22   
AND             9,888.05   

          total_deaths_pm  \
iso_code                    
DZA                 14.89   
AND                660.07   

            population  pop_density  \
iso_code                              
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   

          median_age  gdp_per_capita  \
iso_code                               
DZA            29.10       13,913.84   
AND              NaN             NaN   

          hosp_beds  
iso_code             
DZA            1.90  
AND             NaN

In [8]:
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
demovars_misscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
Name: count, dtype: int64

### 미션 1. 
- 결측치가 3개 이상인 데이터를 추출하세요!
- 추출해야 할 컬럼은  ['location'] + demovars

In [9]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals = covidtotals.set_index('iso_code')
covidtotals.head(1)

lastdate     location  \
iso_code                            
AFG       2020-06-01  Afghanistan   

          total_cases  total_deaths  \
iso_code                              
AFG             15205           257   

          total_cases_pm  \
iso_code                   
AFG               390.59   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   

            population  pop_density  \
iso_code                              
AFG      38,928,341.00        54.42   

          median_age  gdp_per_capita  \
iso_code                               
AFG            18.60        1,803.99   

          hosp_beds  
iso_code             
AFG            0.50

In [10]:
covidtotals.loc[demovars_misscnt >= 3, ['location'] + demovars].T

iso_code             AND       AIA  \
location         Andorra  Anguilla   
population     77,265.00 15,002.00   
pop_density       163.75       NaN   
median_age           NaN       NaN   
gdp_per_capita       NaN       NaN   
hosp_beds            NaN       NaN   

iso_code                                    BES  \
location        Bonaire Sint Eustatius and Saba   
population                            26,221.00   
pop_density                                 NaN   
median_age                                  NaN   
gdp_per_capita                              NaN   
hosp_beds                                   NaN   

iso_code                           VGB  \
location        British Virgin Islands   
population                   30,237.00   
pop_density                     207.97   
median_age                         NaN   
gdp_per_capita                     NaN   
hosp_beds                          NaN   

iso_code                   FRO  \
location        Faeroe Islands   
population           48,865.00   
pop_density              35.31   
median_age                 NaN   
gdp_per_capita             NaN   
hosp_beds                  NaN   

iso_code                     FLK  \
location        Falkland Islands   
population              3,483.00   
pop_density                  NaN   
median_age                   NaN   
gdp_per_capita               NaN   
hosp_beds                    NaN   

iso_code              GIB        GRL  \
location        Gibraltar  Greenland   
population      33,691.00  56,772.00   
pop_density      3,457.10       0.14   
median_age            NaN        NaN   
gdp_per_capita        NaN        NaN   
hosp_beds             NaN        NaN   

iso_code             GGY          IMN  \
location        Guernsey  Isle of Man   
population     67,052.00    85,032.00   
pop_density          NaN       147.87   
median_age           NaN          NaN   
gdp_per_capita       NaN          NaN   
hosp_beds            NaN          NaN   

iso_code              JEY  \
location           Jersey   
population     101,073.00   
pop_density           NaN   
median_age            NaN   
gdp_per_capita        NaN   
hosp_beds             NaN   

iso_code                XKX  \
location             Kosovo   
population     1,932,774.00   
pop_density             NaN   
median_age              NaN   
gdp_per_capita          NaN   
hosp_beds               NaN   

iso_code               MSR  \
location        Montserrat   
population        4,999.00   
pop_density            NaN   
median_age             NaN   
gdp_per_capita         NaN   
hosp_beds              NaN   

iso_code                             MNP  \
location        Northern Mariana Islands   
population                     57,557.00   
pop_density                       119.88   
median_age                           NaN   
gdp_per_capita                       NaN   
hosp_beds                            NaN   

iso_code                 TWN  \
location              Taiwan   
population     23,816,775.00   
pop_density              NaN   
median_age             42.20   
gdp_per_capita           NaN   
hosp_beds                NaN   

iso_code                             TCA  \
location        Turks and Caicos Islands   
population                     38,718.00   
pop_density                        37.31   
median_age                           NaN   
gdp_per_capita                       NaN   
hosp_beds                            NaN   

iso_code            VAT  \
location        Vatican   
population       809.00   
pop_density         NaN   
median_age          NaN   
gdp_per_capita      NaN   
hosp_beds           NaN   

iso_code                   ESH  
location        Western Sahara  
population          597,330.00  
pop_density                NaN  
median_age               28.40  
gdp_per_capita             NaN  
hosp_beds                  NaN

## Index Alignment
- 인덱스의 값끼리 연산이 이뤄지는 것을 말함. Pandas에서 제공함

In [11]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])

# print(s1, "\n", s2)
print(s1 + s2)

a    2
b    4
c    6
d    8
dtype: int64


## 코로나 관련 변수만 추출
- 결측값이 있는지 확인
- 결측값이 있는 국가 하나 존재 / 찾으십시요!!!
- totvars 사용

In [24]:
covidtotals[totvars].isnull().sum(axis=0)
totvarsmisscnt = covidtotals[totvars].isnull().sum(axis=1)
covidtotals.loc[totvarsmisscnt>0].T

iso_code                 HKG
lastdate          2020-05-26
location           Hong Kong
total_cases                0
total_deaths               0
total_cases_pm           NaN
total_deaths_pm          NaN
population      7,496,988.00
pop_density         7,039.71
median_age             44.80
gdp_per_capita     56,054.92
hosp_beds                NaN

In [22]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision = 0)

covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                          labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision = 0)
covidtotalsonly

location  total_cases  \
iso_code                                
AFG          Afghanistan        15205   
ALB              Albania         1137   
DZA              Algeria         9394   
AND              Andorra          764   
AGO               Angola           86   
...                  ...          ...   
VNM              Vietnam          328   
ESH       Western Sahara           23   
YEM                Yemen          323   
ZMB               Zambia         1057   
ZWE             Zimbabwe          178   

          total_deaths  \
iso_code                 
AFG                257   
ALB                 33   
DZA                653   
AND                 51   
AGO                  4   
...                ...   
VNM                  0   
ESH                  1   
YEM                 80   
ZMB                  7   
ZWE                  4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   
...                  ...   
VNM                 3.37   
ESH                38.51   
YEM                10.83   
ZMB                57.50   
ZWE                11.98   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   
...                   ...   
VNM                  0.00   
ESH                  1.67   
YEM                  2.68   
ZMB                  0.38   
ZWE                  0.27   

         total_cases_q total_deaths_q  
iso_code                               
AFG                 높음             높음  
ALB                 중간             중간  
DZA                 높음           매우높음  
AND                 중간             중간  
AGO               매우낮음             낮음  
...                ...            ...  
VNM                 낮음           매우낮음  
ESH               매우낮음           매우낮음  
YEM                 낮음             높음  
ZMB                 중간             낮음  
ZWE                 낮음             낮음  

[210 rows x 7 columns]

In [23]:
pd.crosstab(covidtotalsonly['total_cases_q'],covidtotalsonly['total_deaths_q'])

total_deaths_q  매우낮음  낮음  중간  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
중간                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [27]:
countries = covidtotalsonly[
    (covidtotalsonly['total_cases_q'] == '낮음') & 
    (covidtotalsonly['total_deaths_q'] == '높음')
]

In [28]:
countries

location  total_cases  \
iso_code                         
YEM         Yemen          323   

          total_deaths  \
iso_code                 
YEM                 80   

          total_cases_pm  \
iso_code                   
YEM                10.83   

          total_deaths_pm  \
iso_code                    
YEM                  2.68   

         total_cases_q total_deaths_q  
iso_code                               
YEM                 낮음             높음